### ISSUE TITLE
Mapping of the Descriptor Reports to HID Keyboard Charachteristics 

### ISSUE THREAD

**Issue by mkardan** [chegewara/esp32-hid-keyboard-client#1]
Hi @chegewara,
Many thanks for your amazing help. Just managed to flash ESP32 evaluation card with the HID Keyboard client and seems like my barcode scanner is actually connected to it! :)

A quick question - hopefully- ; regarding the characteristics of HID service I guess I have to use the report mapping somehow -please correct me if I am wrong-. Following is the report structure and the descriptor mapping of the TI device -CC2540- that been used in the barcode scanner respectively:

[CC2540_report_struct.txt](https://github.com/chegewara/esp32-hid-keyboard-client/files/4041286/CC2540_report_struct.txt)
[CC2540_report_map.txt](https://github.com/chegewara/esp32-hid-keyboard-client/files/4041288/CC2540_report_map.txt)

If that is the case are you able to advise how can I interpret the reports to characteristics ( I would like to read the scanned data). I do apologise in advance if this question is not valid.

Cheers,
FakeStar

**Comment by chegewara** [comment]
> Hi @chegewara,
> Many thanks for your amazing help. Just managed to flash ESP32 evaluation card with the HID Keyboard client and seems like my barcode scanner is actually connected to it! :)

It should connect, because its HID device, the problem may be with characteristics.

> A quick question - hopefully- ; regarding the characteristics of HID service I guess I have to use the report mapping somehow -please correct me if I am wrong-. Following is the report structure and the descriptor mapping of the TI device -CC2540- that been used in the barcode scanner respectively:
> 
> [CC2540_report_struct.txt](https://github.com/chegewara/esp32-hid-keyboard-client/files/4041286/CC2540_report_struct.txt)
> [CC2540_report_map.txt](https://github.com/chegewara/esp32-hid-keyboard-client/files/4041288/CC2540_report_map.txt)
> 
> If that is the case are you able to advise how can I interpret the reports to characteristics ( I would like to read the scanned data). I do apologise in advance if this question is not valid.
> 
> Cheers,
> FakeStar

This struct and report map is for HID keyboard, but you need to read report from barcode device. You can do it by reading report map characteristic on esp32 or using nRF connect on android smartphone. Then is hard part to understand it.

**Comment by mkardan** [comment]
Brilliant, thanks a lot for your prompt help/reply. Will do. :)
