### ISSUE TITLE
Is the connection secured enough for a password manager? 

### ISSUE THREAD

**Issue by teezzan** [chegewara/esp32-hid-keyboard-client#4]
Hello,
I want to know if the BLE HID Keyboard is safe enough to transmit passwords over it. I plan to make a BLE based password manager by emulating a Keyboard.
My knowledge is quite limited.
Thanks.

**Comment by chegewara** [comment]
It should be safe as far as bluetooth LE specs says, but you will have to use at least encrypted connection and its advised to use pairing with passkey.

**Comment by teezzan** [comment]
Thanks a lot.
