### ISSUE TITLE
Why I can't find logitech K480 bluetooth keyboard during scanning?

### ISSUE THREAD

**Issue by ziv2013** [chegewara/esp32-hid-keyboard-client#5]
Hi,

I have tried your code in Arduino. But I can't find my logitech K480 bluetooth keyboard during scanning. 

I means I can found other BLE devices such as XiaoMi thermo-hygrometer and TV, but there is no K480 keyboard.

And I have verified this keyboard with my Andriod phone. It works well. 

During pairing with my phone, there would be a code shown one screen. After I input this code one the keyboard, it can be paired with my phone.

Is there any additional settings should I do in my code?

Thanks，

Z.t

**Comment by chegewara** [comment]
Hi,
you cant find it because its classic BT keyboard and this is BLE code.

**Comment by ziv2013** [comment]
Hi,

Thanks. You are right. It's a classic bluetooth keyboard. I tested "https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_hid_host". It works.
