### ISSUE TITLE
No Keystrokes Printed.

### ISSUE THREAD

**Issue by Ranajayy** [chegewara/esp32-hid-keyboard-client#6]
i used this code it does scan and connect to my ble keyboard but nothing gets printed on the serial monitor, the key strokes etc, what is the issue? im using and esp32 on arduino ide 

![d](https://github.com/chegewara/esp32-hid-keyboard-client/assets/84616487/dc6d02fc-73e3-4dd5-9e79-fb13ffcc1af9)

**Comment by chegewara** [comment]
Hi,
hard to say. Maybe this keyboard has more HID characteristics and code is tested when only 1 exists.
You should check with nrf connect app.

**Comment by Ranajayy** [comment]
Thanks for the reply, will do
